"""Generate local WOFF2 shards from the official Noto Sans CJK variable TTFs."""

import argparse
from pathlib import Path
import shutil

from fontTools import subset
from fontTools.ttLib import TTFont


def unicode_ranges(codepoints):
    ranges = []
    start = previous = codepoints[0]
    for codepoint in codepoints[1:] + [None]:
        if codepoint is not None and codepoint == previous + 1:
            previous = codepoint
            continue
        ranges.append(f"U+{start:X}" if start == previous else f"U+{start:X}-{previous:X}")
        start = previous = codepoint
    return ", ".join(ranges)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", type=Path, help="Directory containing the JP/SC/TC variable TTFs and LICENSE")
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[1]
    destination = root / "public/statics/fonts/noto-sans-cjk"
    destination.mkdir(parents=True, exist_ok=True)
    rules = ["/* Generated by scripts/subset-cjk-fonts.py; see the font directory's README.md. */"]

    for region in ("sc", "jp", "tc"):
        source = args.source / f"NotoSansCJK{region}-VF.ttf"
        with TTFont(source) as original:
            codepoints = sorted(original.getBestCmap())
        covered = set()
        for index, offset in enumerate(range(0, len(codepoints), 1024)):
            points = codepoints[offset:offset + 1024]
            options = subset.Options()
            options.layout_features = ["*"]
            options.name_IDs = ["*"]
            options.name_languages = ["*"]
            with TTFont(source) as font:
                subsetter = subset.Subsetter(options=options)
                subsetter.populate(unicodes=points)
                subsetter.subset(font)
                filename = f"{region}-{index:03d}.woff2"
                font.flavor = "woff2"
                font.save(destination / filename)
            with TTFont(destination / filename) as result:
                assert set(points) == set(result.getBestCmap()), filename
                covered.update(result.getBestCmap())
            rules.append(
                "@font-face {\n"
                f'  font-family: "Noto Sans CJK {region.upper()}";\n'
                "  font-style: normal;\n"
                "  font-weight: 100 900;\n"
                "  font-display: swap;\n"
                f'  src: url("/statics/fonts/noto-sans-cjk/{filename}") format("woff2");\n'
                f"  unicode-range: {unicode_ranges(points)};\n"
                "}"
            )
            print(f"{filename}: {len(points)} characters", flush=True)
        assert covered == set(codepoints), region
    shutil.copyfile(args.source / "LICENSE", destination / "LICENSE")
    (root / "src/css/noto-sans-cjk.css").write_text("\n\n".join(rules) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
